apiVersion: v1
kind: Service
# In templates/service.yaml
metadata:
  name: {{ include "user-service-chart.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "user-service-chart.selectorLabels" . | nindent 4 }}
